// User Auth Login Constants
export const USER_SIGNIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_SIGNOUT = 'USER_LOGIN_LOGOUT'

// User Register Constants
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

// User Profile Constants
export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'

// User Profile Update Constants
export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

// User Forgot Password Constants
export const USER_FORGOTPASSWORD_REQUEST = 'USER_FORGOTPASSWORD_REQUEST'
export const USER_FORGOTPASSWORD_SUCCESS = 'USER_FORGOTPASSWORD_SUCCESS'
export const USER_FORGOTPASSWORD_FAIL = 'USER_FORGOTPASSWORD_FAIL'

// User Reset Password Constants
export const USER_RESETPASSWORD_REQUEST = 'USER_RESETPASSWORD_REQUEST'
export const USER_RESETPASSWORD_SUCCESS = 'USER_RESETPASSWORD_SUCCESS'
export const USER_RESETPASSWORD_FAIL = 'USER_RESETPASSWORD_FAIL'
